const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
  "Verily, after every difficulty, there is relief. Surah Al-Sharh ayat 5",
  "People of patience have beautiful endings",
  "You are loved, you are enough, you are worthy",
  "Breathe, this shall too shall pass",
  "It does not matter how slowly you go as long as you do not stop.",
  "The hearts pray for what they desire, but Allah responds with what is better for you.",
  "Keep going. Everything you need will come to you at the perfect time",
  "Just because you took longer than others, that doesn't mean you failed",
  "Aku ada belakang kau Rai 🐧",
  "Allah does not burden a soul beyond that it can bear.",
  "You are eggstraordinary 🍳",
  "One day someone will look at you the same way you look at the moon",
  "You are not alone",
  "You are strong enough to face it, even if it doesn't feel like it right now",
  "There is a past version of you that is so proud of how far you have come.",
  "You mean the world to me",
  "You can't heal from what you pretend isn't hurting you",
  "Trust your intuition, it never lies",
  "Push yourself because no one else is going to do it for you",
  "Allah nampak usaha kau",
  "You have good energy",
  "Your heart is the most beautiful thing about you.",
  "The hearts pray for what they desire, but Allah responds with what is better for you.",
  "Speak kindly to yourself.",
  "You are enough",
  "Many great actions are committed in small struggles",
  "Trust yourself, you know more than you think you do",
  "I am proud of the progress you are making, no matter how small",
  "hehe sayang yee kat kau 🫣",
  "You are doing great",
  "There is always someone rooting for you, even if you think there isn't.",
  "You are my favourite star🌟",
  "You are loved",
  "Have faith in your abilities!",
  "Jangan risau, Allah nampak usaha kau",
  "No more negative self-talk, you are doing great",
  "It is by suffering that human beings become angels.",
  "Aku ada belakang kau Rai",
  "Handle yourself with care",
  "In the middle of a difficulty lies opportunity.",
  "You are strong enough to face it, even if it doesn't feel like it right now",
  "Go! Make the step you were always afraid of",
  "Keep hydrated",
  "Being with you is what I call happiness",
  "You are doing great Fatin Raihanah 🤍",
  "If you lose something you didn't expect to lose. Allah will grant you something you never expected to own",
  "There is always someone out there who are rooting for you",
  "Your body is asking for rest because it knows you are doing your best.",
  "Kalau penat rehat ye, Jangan paksa diri",
  "I am always here for you",]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})
